export const LightTheme = {
    colors: {
        primary: '#2F80ED',
        primaryContainer: '#4F5E7B',
        secondary: '#64748B',
        secondaryContainer: '#F1F5F9',
        surface: '#FFFFFF',
        surfaceVariant: '#F8FAFC',
        background: '#FFFFFF',
        text: {
            primary: '#1E293B',
            secondary: '#64748B',
            disabled: '#94A3B8',
            assistant: '#1E293B',
            user: '#1E293B',
        },
        border: '#E2E8F0',
        error: '#EF4444',
        success: '#10B981',
        warning: '#F59E0B',
        info: '#3B82F6',
        shadow: '#000000',
        inputContainer: '#1E293B',
        userContainer: '#F1F5F9',
        assistantContainer: '#F1F5F9',
        userContent: '#F1F5F9',
        assistantContent: '#F1F5F9',
    },
};

export const DarkTheme = {
    colors: {
        primary: '#60A5FA',
        primaryContainer: '#1E3A8A',
        secondary: '#94A3B8',
        secondaryContainer: '#1E293B',
        surface: '#1E293B',
        surfaceVariant: '#0F172A',
        background: '#0F172A',
        text: {
            primary: '#F8FAFC',
            secondary: '#CBD5E1',
            disabled: '#64748B',
            assistant: '#F8FAFC',
            user: '#F8FAFC',
        },
        border: '#334155',
        error: '#F87171',
        success: '#34D399',
        warning: '#FBBF24',
        info: '#60A5FA',
        shadow: '#FFFFFF',
        inputContainer: '#F8FAFC',
        userContainer: '#1E293B',
        assistantContainer: '#1E293B',
        userContent: '#1E293B',
        assistantContent: '#1E293B',
    },
}; 